name: 海外秒下 + 免登录直链

on:
  workflow_dispatch:

env:
  FILE_NAME: Fedora-IoT-42.raw.xz
  DOWN_URL: https://dl.fedoraproject.org/pub/alt/iot/42/IoT/aarch64/images/Fedora-IoT-raw-42-20250724.1.aarch64.raw.xz

jobs:
  download-and-link:
    runs-on: ubuntu-latest
    steps:
      - name: 安装工具
        run: sudo apt-get update && sudo apt-get install -y aria2 jq

      - name: 海外下载
        run: aria2c -x16 -s16 "${DOWN_URL}" -o "${FILE_NAME}"

      - name: 上传 Artifact（GitHub CDN）
        id: artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FILE_NAME }}
          path: ${{ env.FILE_NAME }}
          retention-days: 1        # 1 小时后自动删除

      - name: 生成免登录直链（带重试）
        id: link
        run: |
          FILE="${FILE_NAME}"
          # 最多等 20 秒入库
          for i in {1..10}; do
            ART_LIST=$(curl -s -H "Authorization: token ${GITHUB_TOKEN}" \
              https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts)
            ARTIFACT_ID=$(echo "$ART_LIST" | jq -r --arg name "$FILE" '.artifacts[] | select(.name==$name) | .id')
            [[ -n "$ARTIFACT_ID" ]] && break || sleep 2
          done

          [[ -z "$ARTIFACT_ID" ]] && { echo "❌ 未找到 Artifact"; exit 1; }

          # 拿真实下载地址（跟踪 302）
          REAL_URL=$(curl -s -I -L -H "Authorization: token ${GITHUB_TOKEN}" \
            https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${ARTIFACT_ID}/archive |
            grep -i "^location" | tail -1 | tr -d '\r' | cut -d' ' -f2)

          [[ -z "$REAL_URL" ]] && { echo "❌ 未获取到直链"; exit 1; }

          echo "---- 免登录直链（1 小时有效） ----"
          echo "$REAL_URL"
          echo "url=$REAL_URL" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
