name: 海外秒下 + 免登录直链

on:
  workflow_dispatch:

env:
  FILE_NAME: Fedora-IoT-42.raw.xz
  DOWN_URL: https://dl.fedoraproject.org/pub/alt/iot/42/IoT/aarch64/images/Fedora-IoT-raw-42-20250724.1.aarch64.raw.xz

jobs:
  download-and-link:
    runs-on: ubuntu-latest
    steps:
      - name: 安装工具
        run: sudo apt-get update && sudo apt-get install -y aria2 jq

      - name: 海外下载
        run: aria2c -x16 -s16 "${DOWN_URL}" -o "${FILE_NAME}"

      - name: 上传 Artifact（GitHub CDN）
        id: artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FILE_NAME }}
          path: ${{ env.FILE_NAME }}
          retention-days: 1        # 1 小时后自动删除

      - name: 调试-获取真实直链
        id: link
        run: |
          set -x          # 打开调试，逐行打印
          FILE="${FILE_NAME}"
          TOKEN="${GITHUB_TOKEN}"

          # 1. 等 Artifact 入库（最多 30 秒）
          for i in {1..15}; do
            echo "[$i] 查询 Artifact..."
            RESP=$(curl -s -H "Authorization: token ${TOKEN}" \
              https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts)
            ARTIFACT_ID=$(echo "$RESP" | jq -r --arg name "$FILE" '.artifacts[]? | select(.name==$name) | .id')
            if [[ -n "$ARTIFACT_ID" ]]; then
              echo "Artifact ID=$ARTIFACT_ID"
              break
            fi
            sleep 2
          done

          if [[ -z "$ARTIFACT_ID" ]]; then
            echo "❌ 未找到 Artifact，原始响应："
            echo "$RESP" | jq .
            exit 1
          fi

          # 2. 请求下载地址（带跟踪）
          DOWN_API="https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${ARTIFACT_ID}/archive"
          echo "请求下载 API：$DOWN_API"

          HEADERS=$(curl -s -I -L -H "Authorization: token ${TOKEN}" "$DOWN_API")
          echo "---- 完整响应头 ----"
          echo "$HEADERS"

          # 3. 提取 Location
          REAL_URL=$(echo "$HEADERS" | grep -i "^location" | tail -1 | awk '{print $2}' | tr -d '\r')
          if [[ -z "$REAL_URL" ]]; then
            echo "❌ 未提取到 Location，请检查响应头"
            exit 1
          fi

          echo "---- 免登录直链 ----"
          echo "$REAL_URL"
          echo "url=$REAL_URL" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
