name: 海外秒下 + 免登录直链

on:
  workflow_dispatch:

env:
  FILE_NAME: Fedora-IoT-42.raw.xz
  DOWN_URL: https://dl.fedoraproject.org/pub/alt/iot/42/IoT/aarch64/images/Fedora-IoT-raw-42-20250724.1.aarch64.raw.xz

jobs:
  download-and-link:
    runs-on: ubuntu-latest
    steps:
      - name: 安装工具
        run: sudo apt-get update && sudo apt-get install -y aria2 jq

      - name: 海外下载
        run: aria2c -x16 -s16 "${DOWN_URL}" -o "${FILE_NAME}"

      - name: 上传 Artifact（GitHub CDN）
        id: artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FILE_NAME }}
          path: ${{ env.FILE_NAME }}
          retention-days: 1        # 1 小时后自动删除

      - name: 生成免登录直链（1 小时有效）
        id: link
        run: |
          # 等待 Artifact 入库（GitHub API 有 1-3 秒延迟）
          sleep 5

          # 获取 Artifact ID
          ARTIFACT_ID=$(curl -s -H "Authorization: token ${GITHUB_TOKEN}" \
            https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts \
            | jq -r '.artifacts[] | select(.name=="${{ env.FILE_NAME }}") | .id')

          # 换真实下载地址（302 后的 location）
          REAL_URL=$(curl -s -I -H "Authorization: token ${GITHUB_TOKEN}" \
            https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${ARTIFACT_ID}/archive \
            | grep -i location | cut -d' ' -f2 | tr -d '\r')

          echo "---- 免登录直链（1 小时有效）----"
          echo "${REAL_URL}"
          echo "---- 复制到 IDM / aria2 即可满速 ----"

          # 可选：把链接写进 GitHub 输出，方便后续步骤调用
          echo "url=${REAL_URL}" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
